services:
  bot:
    container_name: bbot-app
    image: brunofunnie/butecobot-reloaded-app:latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./builds/.env:/app/.env
      - ./storage/:/app/storage/
      - ./storage/logs/:/app/logs/
    networks:
      bbot:

  mysql:
    container_name: bbot-mysql
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=butecobot
      - MYSQL_USER=butecobot
      - MYSQL_PASSWORD=butecobot
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/confs/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
       bbot:

  pma:
    container_name: bbot-pma
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=2048M
      - UPLOAD_LIMIT=2048M
    networks:
       bbot:

  mongo:
    container_name: bbot-mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db
    networks:
       bbot:

  mongo-express:
    container_name: bbot-mongo-express
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootd
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
       bbot:

  valkey:
    container_name: bbot-valkey
    image: valkey/valkey
    ports:
      - 6379:6379
    command: valkey-server --save 20 1 --loglevel warning --requirepass valkey
    volumes:
      - valkey:/data
    networks:
       bbot:

  mpit:
    container_name: bbot-mailpit
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - TZ=America/Sao_Paulo
    networks:
       bbot:

networks:
  bbot:

volumes:
  mysql:
  valkey:
  mongodb:
